import "~/styles/globals.css";

import { type Metadata } from "next";
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { CartProvider } from "~/contexts/CartContext";
import { OrderProvider } from "~/contexts/OrderContext";
import { ToastProvider } from "~/components/Toast";
import TelegramLoader from "~/components/TelegramLoader";
import ForceLightTheme from "~/components/ForceLightTheme";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <TRPCReactProvider>
          <CartProvider>
            <OrderProvider>
              <ToastProvider>
                <TelegramLoader />
                <ForceLightTheme />
                {children}
              </ToastProvider>
            </OrderProvider>
          </CartProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
